void SCEprint(){

  // read the Tree generated by tree1w and fill two histograms
  // note that we use "new" to create the TFile and TTree objects,
  // to keep them alive after leaving this function.
  TFile *f = new TFile("ntuple.root");
  TTree *tt = (TTree*)f->Get("emJetAnalyzer/emJetTree");

  Int_t nVtx, event;
  Float_t met_pt, met_phi;
  vector<int> *jet_index=new vector<int>;
  vector<int> *jet_source=new vector<int>;
  vector<float> *jet_pt = new vector<float>;
  vector<float> *jet_eta = new vector<float>;
  vector<float> *jet_phi = new vector<float>;
  vector<float> *jet_alphaMax = new vector<float>;
  vector<vector<float> > *track_pt = 0;

  tt->SetBranchAddress("nVtx",&nVtx);
  tt->SetBranchAddress("event",&event);
  tt->SetBranchAddress("met_pt",&met_pt);
  tt->SetBranchAddress("met_phi",&met_phi);
  tt->SetBranchAddress("jet_index",&jet_index);
  tt->SetBranchAddress("jet_source",&jet_source);
  tt->SetBranchAddress("jet_pt",&jet_pt);
  tt->SetBranchAddress("jet_eta",&jet_eta);
  tt->SetBranchAddress("jet_phi",&jet_phi);
  tt->SetBranchAddress("jet_alphaMax",&jet_alphaMax);
  tt->SetBranchAddress("track_pt",&track_pt);

  // create a histograms
  TH1F *hpt   = new TH1F("hpt","pt distribution",100,0.,500.);
  TH1F *halpha   = new TH1F("halpha","alphaMax distribution",100,0.,100.);

  //read all entries and fill the histograms
  Int_t nentries = (Int_t)tt->GetEntries();
  for (Int_t i=0; i<nentries; i++) {
    tt->GetEntry(i);
    cout<<"event number is "<<event<<" number of vertex is "<<nVtx<<endl;
    cout<<" pt eta phi alphaMax "<<endl;
    for(Int_t j=0; j<(*jet_index).size(); j++) {
      cout<<" jet "<<(*jet_pt)[j]<<" "<<(*jet_eta)[j]<<" "<<(*jet_phi)[j]<<" "<<(*jet_alphaMax)[j]<<" "<<endl;
      hpt->Fill((*jet_pt)[j]);
      halpha->Fill((*jet_alphaMax)[j]);
      vector<float> track_pt_for_current_jet = track_pt->at(j);
      cout << "track number\tpt"<<endl;
      for (unsigned itrack=0; itrack<track_pt_for_current_jet.size(); itrack++) {
        cout << itrack << "\t" << track_pt_for_current_jet[itrack] << endl;
      }
    }
  }
  // We do not close the file. We want to keep the generated
  // histograms we open a browser and the TreeViewer
  if (gROOT->IsBatch()) return;
  TCanvas *c1 = new TCanvas("c1","Vertex Plots",200,10,700,500);
  hpt->Draw();
  c1->Modified();
  c1->Update();
  //  t1->StartViewer();

  tt->ResetBranchAddresses();
  delete jet_index;
  delete jet_source;
  delete jet_pt;
  delete jet_eta;
  delete jet_phi;
  delete jet_alphaMax;



  //In the browser, click on "ROOT Files", then on "tree1.root"
  //You can click on the histogram icons in the right panel to draw
  //them in the TreeViewer, follow the instructions in the Help.
}
