#include <iostream>
#include <iomanip>
#include <locale>

#include <TROOT.h>
#include <TFile.h>

#include "vector"
using std::vector;

#include <TStyle.h>
#include <TCanvas.h>


void fakerates() {


    // read the Tree generated by tree1w and fill two histograms
    // note that we use "new" to create the TFile and TTree objects,
    // to keep them alive after leaving this function.




    gStyle->SetOptStat(111111);

    TString canvName = "Fig_";
    canvName += "haha";

    //  if( writeExtraText ) canvName += "-prelim";
    //if( iPos%10==0 ) canvName += "-out";                                        
    //else if( iPos%10==1 ) canvName += "-left";                                  
    //else if( iPos%10==2 )  canvName += "-center";                               
    //else if( iPos%10==3 )  canvName += "-right";                                
    int W = 800;
    int H = 600;
    TCanvas* canv = new TCanvas(canvName,canvName,50,50,W,H);
    // references for T, B, L, R                                                  
    float T = 0.08*H;
    float B = 0.12*H;
    float L = 0.12*W;
    float R = 0.04*W;

    canv->SetFillColor(0);
    canv->SetBorderMode(0);
    canv->SetFrameFillStyle(0);
    canv->SetFrameBorderMode(0);
    canv->SetLeftMargin( L/W );
    canv->SetRightMargin( R/W );
    canv->SetTopMargin( T/H );
    canv->SetBottomMargin( B/H );
    canv->SetTickx(0);
    canv->SetTicky(0);


    int n_ = 2;

    float x1_l = 0.9;
    //  float x1_l = 0.75;                                                                  
    float y1_l = 0.80;

    float dx_l = 0.60;
    float dy_l = 0.1;
    float x0_l = x1_l-dx_l;
    float y0_l = y1_l-dy_l;

    TLegend *lgd = new TLegend(x0_l,y0_l,x1_l, y1_l);
    lgd->SetBorderSize(0); lgd->SetTextSize(0.04); lgd->SetTextFont(62); lgd->SetFillColor(0);

    TFile *f = new TFile("histos/analysis_20170223_v0_p20170227/SumHistsQCD74.root");

    //float hltBins[19] = {0.,1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,12.,14.,16.,18.,20.,25.,30.,40.};
    TH1F* nhist = static_cast<TH1F*>(f->Get("hfr_ntrkpt1n")->Clone());
    TH1F* dhist = static_cast<TH1F*>(f->Get("hfr_ntrkpt1d")->Clone());
    TH1F* rhist = static_cast<TH1F*>(f->Get("hfr_ntrkpt1n")->Clone("fakerate"));

    bool divideOK = rhist->Divide(rhist, dhist, 1., .1, "cl=0.683 cp");
    if (!divideOK) return;
    //rhist->Divide(dhist,"cl=0.683 cp");
    rhist->SetMaximum(0.02);
    rhist->GetXaxis()->SetTitle("Number of p_{T}>1GeV tracks");
    rhist->GetYaxis()->SetTitle("#epsilon_{jet tagger}");

    rhist->SetDirectory(0);
    rhist->SetLineColor(3);
    rhist->SetLineWidth(3);
    rhist->SetStats(0);
    rhist->Draw("");
    rhist->Draw();

    lgd->AddEntry(rhist, "CR: N_{tagged jets} < 2", "l");

    lgd->Draw();


    canv->Update();
    canv->RedrawAxis();
    canv->GetFrame()->Draw();


    return;


}
